---
- name: Restart a Windows Service
  hosts: windows
  gather_facts: no
  vars:
    service_name: "Spooler" # Specify the service you want to restart
  tasks:
    - name: Restart a service
      ansible.windows.win_service:
        name: "{{ service_name }}"
        state: restarted