---
- name: Starting a service in Windows
  hosts: windows
  gather_facts: no
  vars:
    service_name: "Spooler" # Change this to the name of the service you want to start
  tasks:
    - name: Start the service
      ansible.windows.win_service:
        name: "{{ service_name }}"
        state: started